spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  data:
    mongodb:
      uri: ${MONGO_URL:${app.mongodb.default-uri}}
      database: ${MONGO_DATABASE:${app.mongodb.default-database}}
app:
  mongodb:
    default-uri: mongodb://localhost
    default-database: admin
  twitch:
    client-id: ${TWITCH_CLIENTID:test}
    client-secret: ${TWITCH_SECRET:test}
  discord:
    token: ${DISCORD_TOKEN:test}